sudo: required
dist: trusty

language: node_js
node_js: 8

install:
  - yarn global add lix haxe-travix
  - lix download

script:
  - travix interp
  - travix neko
  - travix neko -D concurrent
  - travix python
  - travix node
  # - travix flash
  - travix java
  - travix java -D concurrent
  - travix cpp
  - travix cpp -D concurrent
  - travix cs
  - travix php
