sudo: required
dist: trusty

language: node_js
node_js: 8

install:
  - npm install lix -g
  - lix download

script:
  - lix run travix interp
  - lix run travix neko
  - lix run travix neko -D concurrent
  - lix run travix python
  - lix run travix node
  # - lix run travix flash
  - lix run travix java -D jvm
  - lix run travix java -D concurrent -D jvm
  - lix run travix cpp
  - lix run travix cpp -D concurrent
  - lix run travix cs
  - lix run travix php
