sudo: required
dist: trusty

language: haxe

haxe:
  - "3.2.1"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix interp
  - haxelib run travix neko
  - haxelib run travix neko -D concurrent
  - haxelib run travix python
  - haxelib run travix node
  # - haxelib run travix flash
  - haxelib run travix java
  - haxelib run travix java -D concurrent
  - haxelib run travix cpp
  - haxelib run travix cpp -D concurrent
  - haxelib run travix cs
  - haxelib run travix php
